# Generated by Django 6.0.5 on 2026-05-08 16:03

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSpecialistProfile',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('avatar', models.TextField(blank=True, help_text='Фотография или изображение профиля специалиста.', max_length=100, null=True, verbose_name='аватар')),
                ('level', models.CharField(choices=[('intern', 'Стажёр'), ('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior'), ('lead', 'Lead')], default='junior', max_length=20, verbose_name='уровень')),
                ('status', models.CharField(choices=[('looking', 'Ищу проект'), ('open', 'Открыт к предложениям'), ('busy', 'Занят'), ('hidden', 'Скрыт')], default='looking', max_length=20, verbose_name='статус доступности')),
                ('participation_format', models.CharField(choices=[('remote', 'Удалённо'), ('hybrid', 'Гибрид'), ('office', 'Офис'), ('any', 'Любой формат')], default='remote', max_length=20, verbose_name='формат участия')),
                ('bio', models.TextField(blank=True, help_text='Краткое описание опыта, интересов и целей специалиста.', verbose_name='о себе')),
                ('experience_years', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)], verbose_name='опыт в годах')),
                ('weekly_hours', models.PositiveSmallIntegerField(default=10, help_text='Сколько часов в неделю специалист готов уделять проектам.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(80)], verbose_name='часов в неделю')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='город')),
                ('timezone', models.CharField(blank=True, help_text='Например: Europe/Moscow.', max_length=50, verbose_name='часовой пояс')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub')),
                ('gitlab_url', models.URLField(blank=True, verbose_name='GitLab')),
                ('portfolio_url', models.URLField(blank=True, verbose_name='портфолио')),
                ('telegram', models.CharField(blank=True, help_text='Контакт для связи, например: @username.', max_length=100, verbose_name='Telegram')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='дата изменения')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='создал')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('main_role', models.ForeignKey(blank=True, db_constraint=False, help_text='Основная профессиональная роль специалиста.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='directories.role', verbose_name='основная роль')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='изменил')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, help_text='Пользователь, которому принадлежит профиль специалиста.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'история изменений',
                'verbose_name_plural': 'historical профили специалистов',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SpecialistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, help_text='Фотография или изображение профиля специалиста.', null=True, upload_to='specialists/avatars/', verbose_name='аватар')),
                ('level', models.CharField(choices=[('intern', 'Стажёр'), ('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior'), ('lead', 'Lead')], default='junior', max_length=20, verbose_name='уровень')),
                ('status', models.CharField(choices=[('looking', 'Ищу проект'), ('open', 'Открыт к предложениям'), ('busy', 'Занят'), ('hidden', 'Скрыт')], default='looking', max_length=20, verbose_name='статус доступности')),
                ('participation_format', models.CharField(choices=[('remote', 'Удалённо'), ('hybrid', 'Гибрид'), ('office', 'Офис'), ('any', 'Любой формат')], default='remote', max_length=20, verbose_name='формат участия')),
                ('bio', models.TextField(blank=True, help_text='Краткое описание опыта, интересов и целей специалиста.', verbose_name='о себе')),
                ('experience_years', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)], verbose_name='опыт в годах')),
                ('weekly_hours', models.PositiveSmallIntegerField(default=10, help_text='Сколько часов в неделю специалист готов уделять проектам.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(80)], verbose_name='часов в неделю')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='город')),
                ('timezone', models.CharField(blank=True, help_text='Например: Europe/Moscow.', max_length=50, verbose_name='часовой пояс')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub')),
                ('gitlab_url', models.URLField(blank=True, verbose_name='GitLab')),
                ('portfolio_url', models.URLField(blank=True, verbose_name='портфолио')),
                ('telegram', models.CharField(blank=True, help_text='Контакт для связи, например: @username.', max_length=100, verbose_name='Telegram')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_specialist_profiles', to=settings.AUTH_USER_MODEL, verbose_name='создал')),
                ('main_role', models.ForeignKey(blank=True, help_text='Основная профессиональная роль специалиста.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_specialists', to='directories.role', verbose_name='основная роль')),
                ('preferred_roles', models.ManyToManyField(blank=True, help_text='Роли, в которых специалист хотел бы участвовать в проектах.', related_name='preferred_by_specialists', to='directories.role', verbose_name='интересующие роли')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_specialist_profiles', to=settings.AUTH_USER_MODEL, verbose_name='изменил')),
                ('user', models.OneToOneField(help_text='Пользователь, которому принадлежит профиль специалиста.', on_delete=django.db.models.deletion.CASCADE, related_name='specialist_profile', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'профиль специалиста',
                'verbose_name_plural': 'профили специалистов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpecialistTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('basic', 'Базовый'), ('confident', 'Уверенный'), ('advanced', 'Продвинутый'), ('expert', 'Эксперт')], default='confident', max_length=20, verbose_name='уровень владения')),
                ('years_of_experience', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)], verbose_name='опыт в годах')),
                ('is_primary', models.BooleanField(default=False, help_text='Отметить, если технология является одной из основных.', verbose_name='ключевой навык')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата добавления')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialist_technologies', to='specialists.specialistprofile', verbose_name='специалист')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialist_technologies', to='directories.technology', verbose_name='технология')),
            ],
            options={
                'verbose_name': 'технология специалиста',
                'verbose_name_plural': 'технологии специалистов',
                'ordering': ['specialist', '-is_primary', 'technology__name'],
            },
        ),
        migrations.AddField(
            model_name='specialistprofile',
            name='technologies',
            field=models.ManyToManyField(related_name='specialists', through='specialists.SpecialistTechnology', to='directories.technology', verbose_name='технологии'),
        ),
        migrations.AddConstraint(
            model_name='specialisttechnology',
            constraint=models.UniqueConstraint(fields=('specialist', 'technology'), name='unique_specialist_technology'),
        ),
    ]
