# Generated by Django 6.0.5 on 2026-05-10 21:49

import apps.common_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalspecialistprofile',
            name='avatar',
            field=models.TextField(blank=True, help_text='Фотография или изображение профиля специалиста.', max_length=100, null=True, validators=[apps.common_validators.validate_avatar_image], verbose_name='аватар'),
        ),
        migrations.AlterField(
            model_name='specialistprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Фотография или изображение профиля специалиста.', null=True, upload_to='specialists/avatars/', validators=[apps.common_validators.validate_avatar_image], verbose_name='аватар'),
        ),
    ]
