# Generated by Django 6.0.6 on 2026-06-09 23:03

import apps.common_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0002_alter_historicalspecialistprofile_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalspecialistprofile',
            name='timezone',
            field=models.CharField(blank=True, help_text='Например: Europe/Moscow.', max_length=50, validators=[apps.common_validators.validate_iana_timezone], verbose_name='часовой пояс'),
        ),
        migrations.AlterField(
            model_name='specialistprofile',
            name='timezone',
            field=models.CharField(blank=True, help_text='Например: Europe/Moscow.', max_length=50, validators=[apps.common_validators.validate_iana_timezone], verbose_name='часовой пояс'),
        ),
    ]
