# Generated by Django 6.0.6 on 2026-06-09 23:03

import django.db.models.functions.text
from django.db import migrations, models


def normalize_user_emails(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    seen = {}

    for user in User.objects.exclude(email="").order_by("pk"):
        normalized = user.email.strip().lower()
        if normalized in seen:
            raise RuntimeError(
                "Нельзя добавить unique email: пользователи "
                f"{seen[normalized]} и {user.pk} используют {normalized}."
            )
        seen[normalized] = user.pk
        if user.email != normalized:
            User.objects.filter(pk=user.pk).update(email=normalized)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RunPython(normalize_user_emails, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), condition=models.Q(('email', ''), _negated=True), name='unique_user_email_ci'),
        ),
    ]
