# Generated by Django 6.0.5 on 2026-05-08 16:12

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('specialists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalApplication',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('message', models.TextField(blank=True, help_text='Сопроводительное сообщение специалиста владельцу проекта.', verbose_name='сообщение')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('accepted', 'Принят'), ('rejected', 'Отклонён'), ('cancelled', 'Отменён')], default='pending', max_length=20, verbose_name='статус отклика')),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата отклика')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='дата рассмотрения')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.project', verbose_name='проект')),
                ('reviewed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='рассмотрел')),
                ('specialist', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='specialists.specialistprofile', verbose_name='специалист')),
                ('vacancy', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.projectvacancy', verbose_name='открытая роль')),
            ],
            options={
                'verbose_name': 'история изменений',
                'verbose_name_plural': 'historical отклики',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalInvitation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('message', models.TextField(blank=True, help_text='Сообщение владельца проекта специалисту.', verbose_name='сообщение')),
                ('status', models.CharField(choices=[('pending', 'Ожидает ответа'), ('accepted', 'Принято'), ('declined', 'Отклонено'), ('cancelled', 'Отменено'), ('expired', 'Истекло')], default='pending', max_length=20, verbose_name='статус приглашения')),
                ('invited_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата приглашения')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='дата ответа')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='пригласил')),
                ('project', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.project', verbose_name='проект')),
                ('specialist', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='specialists.specialistprofile', verbose_name='специалист')),
                ('vacancy', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.projectvacancy', verbose_name='открытая роль')),
            ],
            options={
                'verbose_name': 'история изменений',
                'verbose_name_plural': 'historical приглашения',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, help_text='Сопроводительное сообщение специалиста владельцу проекта.', verbose_name='сообщение')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('accepted', 'Принят'), ('rejected', 'Отклонён'), ('cancelled', 'Отменён')], default='pending', max_length=20, verbose_name='статус отклика')),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата отклика')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='дата рассмотрения')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='projects.project', verbose_name='проект')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL, verbose_name='рассмотрел')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='specialists.specialistprofile', verbose_name='специалист')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='projects.projectvacancy', verbose_name='открытая роль')),
            ],
            options={
                'verbose_name': 'отклик',
                'verbose_name_plural': 'отклики',
                'ordering': ['-applied_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'accepted'])), fields=('project', 'vacancy', 'specialist'), name='unique_active_application_for_vacancy')],
            },
        ),
        migrations.CreateModel(
            name='FavoriteProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата добавления')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='projects.project', verbose_name='проект')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_projects', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'избранный проект',
                'verbose_name_plural': 'избранные проекты',
                'ordering': ['-added_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'project'), name='unique_favorite_project')],
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, help_text='Сообщение владельца проекта специалисту.', verbose_name='сообщение')),
                ('status', models.CharField(choices=[('pending', 'Ожидает ответа'), ('accepted', 'Принято'), ('declined', 'Отклонено'), ('cancelled', 'Отменено'), ('expired', 'Истекло')], default='pending', max_length=20, verbose_name='статус приглашения')),
                ('invited_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата приглашения')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='дата ответа')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL, verbose_name='пригласил')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='projects.project', verbose_name='проект')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='specialists.specialistprofile', verbose_name='специалист')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='projects.projectvacancy', verbose_name='открытая роль')),
            ],
            options={
                'verbose_name': 'приглашение',
                'verbose_name_plural': 'приглашения',
                'ordering': ['-invited_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('project', 'vacancy', 'specialist'), name='unique_pending_invitation_for_vacancy')],
            },
        ),
    ]
