# Generated by Django 6.0.6 on 2026-06-09 12:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
        ('projects', '0006_historicalprojectmembership_vacancy_and_more'),
        ('specialists', '0002_alter_historicalspecialistprofile_avatar_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='application',
            name='unique_active_application_for_vacancy',
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('project', 'vacancy', 'specialist'), name='unique_active_application_for_vacancy'),
        ),
    ]
