# Generated by Django 6.0.6 on 2026-06-09 12:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_remove_application_unique_active_application_for_vacancy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='message',
            field=models.TextField(blank=True, help_text='Краткий комментарий специалиста к отклику. До 1000 символов.', max_length=1000, validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='комментарий к отклику'),
        ),
        migrations.AlterField(
            model_name='historicalapplication',
            name='message',
            field=models.TextField(blank=True, help_text='Краткий комментарий специалиста к отклику. До 1000 символов.', max_length=1000, validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='комментарий к отклику'),
        ),
        migrations.AlterField(
            model_name='historicalinvitation',
            name='message',
            field=models.TextField(blank=True, help_text='Краткий текст приглашения специалиста в проект. До 1000 символов.', max_length=1000, validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='текст приглашения'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='message',
            field=models.TextField(blank=True, help_text='Краткий текст приглашения специалиста в проект. До 1000 символов.', max_length=1000, validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='текст приглашения'),
        ),
    ]
