# Generated by Django 6.0.6 on 2026-06-09 23:03

from django.db import migrations, models


def replace_cancelled_statuses(apps, schema_editor):
    Application = apps.get_model("interactions", "Application")
    HistoricalApplication = apps.get_model(
        "interactions", "HistoricalApplication"
    )
    Invitation = apps.get_model("interactions", "Invitation")
    HistoricalInvitation = apps.get_model(
        "interactions", "HistoricalInvitation"
    )

    Application.objects.filter(status="cancelled").update(status="rejected")
    HistoricalApplication.objects.filter(status="cancelled").update(
        status="rejected"
    )
    Invitation.objects.filter(status="cancelled").update(status="declined")
    HistoricalInvitation.objects.filter(status="cancelled").update(
        status="declined"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0003_alter_application_message_and_more'),
    ]

    operations = [
        migrations.RunPython(replace_cancelled_statuses, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'На рассмотрении'), ('accepted', 'Принят'), ('rejected', 'Отклонён')], default='pending', max_length=20, verbose_name='статус отклика'),
        ),
        migrations.AlterField(
            model_name='historicalapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'На рассмотрении'), ('accepted', 'Принят'), ('rejected', 'Отклонён')], default='pending', max_length=20, verbose_name='статус отклика'),
        ),
        migrations.AlterField(
            model_name='historicalinvitation',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает ответа'), ('accepted', 'Принято'), ('declined', 'Отклонено'), ('expired', 'Истекло')], default='pending', max_length=20, verbose_name='статус приглашения'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает ответа'), ('accepted', 'Принято'), ('declined', 'Отклонено'), ('expired', 'Истекло')], default='pending', max_length=20, verbose_name='статус приглашения'),
        ),
    ]
