# Generated by Django 6.0.5 on 2026-05-08 16:07

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directories', '0001_initial'),
        ('specialists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProject',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='название проекта')),
                ('slug', models.SlugField(blank=True, help_text='Используется для будущей детальной страницы проекта.', max_length=220, verbose_name='URL-идентификатор')),
                ('short_description', models.CharField(help_text='Короткое описание для карточки проекта.', max_length=300, verbose_name='краткое описание')),
                ('description', models.TextField(verbose_name='подробное описание')),
                ('goal', models.TextField(help_text='Что проект должен решить или какой результат должен получить.', verbose_name='цель проекта')),
                ('cover_image', models.TextField(blank=True, max_length=100, null=True, verbose_name='обложка проекта')),
                ('stage', models.CharField(choices=[('idea', 'Идея'), ('prototype', 'Прототип'), ('mvp', 'MVP'), ('development', 'Разработка'), ('launch', 'Запуск'), ('growth', 'Развитие'), ('paused', 'Пауза'), ('finished', 'Завершён')], default='idea', max_length=30, verbose_name='стадия')),
                ('participation_format', models.CharField(choices=[('free', 'Энтузиазм'), ('paid', 'Оплачиваемо'), ('equity', 'Доля'), ('mixed', 'Смешанный формат'), ('educational', 'Учебный проект')], default='free', max_length=30, verbose_name='формат участия')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('moderation', 'На модерации'), ('published', 'Опубликован'), ('closed', 'Закрыт'), ('archived', 'Архив')], default='draft', max_length=30, verbose_name='статус')),
                ('repository_url', models.URLField(blank=True, verbose_name='ссылка на репозиторий')),
                ('demo_url', models.URLField(blank=True, verbose_name='демо-ссылка')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='дата изменения')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='создал')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, db_constraint=False, help_text='Пользователь, который создал и ведёт проект.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='владелец проекта')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='изменил')),
            ],
            options={
                'verbose_name': 'история изменений',
                'verbose_name_plural': 'historical проекты',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='название проекта')),
                ('slug', models.SlugField(blank=True, help_text='Используется для будущей детальной страницы проекта.', max_length=220, unique=True, verbose_name='URL-идентификатор')),
                ('short_description', models.CharField(help_text='Короткое описание для карточки проекта.', max_length=300, verbose_name='краткое описание')),
                ('description', models.TextField(verbose_name='подробное описание')),
                ('goal', models.TextField(help_text='Что проект должен решить или какой результат должен получить.', verbose_name='цель проекта')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='projects/covers/', verbose_name='обложка проекта')),
                ('stage', models.CharField(choices=[('idea', 'Идея'), ('prototype', 'Прототип'), ('mvp', 'MVP'), ('development', 'Разработка'), ('launch', 'Запуск'), ('growth', 'Развитие'), ('paused', 'Пауза'), ('finished', 'Завершён')], default='idea', max_length=30, verbose_name='стадия')),
                ('participation_format', models.CharField(choices=[('free', 'Энтузиазм'), ('paid', 'Оплачиваемо'), ('equity', 'Доля'), ('mixed', 'Смешанный формат'), ('educational', 'Учебный проект')], default='free', max_length=30, verbose_name='формат участия')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('moderation', 'На модерации'), ('published', 'Опубликован'), ('closed', 'Закрыт'), ('archived', 'Архив')], default='draft', max_length=30, verbose_name='статус')),
                ('repository_url', models.URLField(blank=True, verbose_name='ссылка на репозиторий')),
                ('demo_url', models.URLField(blank=True, verbose_name='демо-ссылка')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='создал')),
                ('owner', models.ForeignKey(help_text='Пользователь, который создал и ведёт проект.', on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL, verbose_name='владелец проекта')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_projects', to=settings.AUTH_USER_MODEL, verbose_name='изменил')),
            ],
            options={
                'verbose_name': 'проект',
                'verbose_name_plural': 'проекты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalProjectVacancy',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(help_text='Например: Junior Frontend-разработчик.', max_length=200, verbose_name='название открытой роли')),
                ('description', models.TextField(verbose_name='описание роли')),
                ('required_level', models.CharField(choices=[('intern', 'Стажёр'), ('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior'), ('lead', 'Lead')], default='junior', max_length=20, verbose_name='требуемый уровень')),
                ('required_count', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='требуется человек')),
                ('current_count', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='уже набрано')),
                ('status', models.CharField(choices=[('open', 'Открыта'), ('paused', 'На паузе'), ('closed', 'Закрыта')], default='open', max_length=20, verbose_name='статус')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='дата изменения')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='directories.role', verbose_name='роль')),
                ('project', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.project', verbose_name='проект')),
            ],
            options={
                'verbose_name': 'история изменений',
                'verbose_name_plural': 'historical открытые роли проектов',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProjectMembership',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('paused', 'На паузе'), ('left', 'Покинул проект')], default='active', max_length=20, verbose_name='статус участия')),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата вступления')),
                ('left_at', models.DateTimeField(blank=True, null=True, verbose_name='дата выхода')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('added_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='добавил')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='directories.role', verbose_name='роль в команде')),
                ('specialist', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='specialists.specialistprofile', verbose_name='специалист')),
                ('project', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.project', verbose_name='проект')),
            ],
            options={
                'verbose_name': 'история изменений',
                'verbose_name_plural': 'historical участники команд',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='projects/files/', verbose_name='файл')),
                ('file_type', models.CharField(choices=[('document', 'Документ'), ('image', 'Изображение'), ('presentation', 'Презентация'), ('archive', 'Архив'), ('other', 'Другое')], default='other', max_length=30, verbose_name='тип файла')),
                ('title', models.CharField(max_length=200, verbose_name='название файла')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата загрузки')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='projects.project', verbose_name='проект')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_project_files', to=settings.AUTH_USER_MODEL, verbose_name='загрузил')),
            ],
            options={
                'verbose_name': 'файл проекта',
                'verbose_name_plural': 'файлы проектов',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('paused', 'На паузе'), ('left', 'Покинул проект')], default='active', max_length=20, verbose_name='статус участия')),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата вступления')),
                ('left_at', models.DateTimeField(blank=True, null=True, verbose_name='дата выхода')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_project_memberships', to=settings.AUTH_USER_MODEL, verbose_name='добавил')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='projects.project', verbose_name='проект')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_memberships', to='directories.role', verbose_name='роль в команде')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to='specialists.specialistprofile', verbose_name='специалист')),
            ],
            options={
                'verbose_name': 'участник команды',
                'verbose_name_plural': 'участники команд',
                'ordering': ['project', 'role__name', 'specialist'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(related_name='team_projects', through='projects.ProjectMembership', to='specialists.specialistprofile', verbose_name='участники команды'),
        ),
        migrations.CreateModel(
            name='ProjectTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=True, verbose_name='обязательная технология')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата добавления')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_technologies', to='projects.project', verbose_name='проект')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_technologies', to='directories.technology', verbose_name='технология')),
            ],
            options={
                'verbose_name': 'технология проекта',
                'verbose_name_plural': 'технологии проектов',
                'ordering': ['project', 'technology__name'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(related_name='projects', through='projects.ProjectTechnology', to='directories.technology', verbose_name='технологии'),
        ),
        migrations.CreateModel(
            name='ProjectVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например: Junior Frontend-разработчик.', max_length=200, verbose_name='название открытой роли')),
                ('description', models.TextField(verbose_name='описание роли')),
                ('required_level', models.CharField(choices=[('intern', 'Стажёр'), ('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior'), ('lead', 'Lead')], default='junior', max_length=20, verbose_name='требуемый уровень')),
                ('required_count', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='требуется человек')),
                ('current_count', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='уже набрано')),
                ('status', models.CharField(choices=[('open', 'Открыта'), ('paused', 'На паузе'), ('closed', 'Закрыта')], default='open', max_length=20, verbose_name='статус')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='projects.project', verbose_name='проект')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_vacancies', to='directories.role', verbose_name='роль')),
            ],
            options={
                'verbose_name': 'открытая роль проекта',
                'verbose_name_plural': 'открытые роли проектов',
                'ordering': ['project', 'role__name', 'title'],
            },
        ),
        migrations.AddConstraint(
            model_name='projectmembership',
            constraint=models.UniqueConstraint(fields=('project', 'specialist', 'role'), name='unique_project_specialist_role'),
        ),
        migrations.AddConstraint(
            model_name='projecttechnology',
            constraint=models.UniqueConstraint(fields=('project', 'technology'), name='unique_project_technology'),
        ),
    ]
