# Generated by Django 6.0.5 on 2026-05-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='projectvacancy',
            constraint=models.CheckConstraint(condition=models.Q(('current_count__lte', models.F('required_count'))), name='vacancy_current_count_lte_required_count'),
        ),
    ]
