# Generated by Django 6.0.5 on 2026-05-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectvacancy_vacancy_current_count_lte_required_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproject',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, help_text='Используется для будущей детальной страницы проекта.', max_length=220, verbose_name='URL-идентификатор'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, help_text='Используется для будущей детальной страницы проекта.', max_length=220, unique=True, verbose_name='URL-идентификатор'),
        ),
    ]
