# Generated by Django 6.0.5 on 2026-05-10 21:49

import apps.common_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_historicalproject_slug_alter_project_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproject',
            name='cover_image',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[apps.common_validators.validate_project_cover_image], verbose_name='обложка проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/covers/', validators=[apps.common_validators.validate_project_cover_image], verbose_name='обложка проекта'),
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='file',
            field=models.FileField(upload_to='projects/files/', validators=[apps.common_validators.validate_project_file], verbose_name='файл'),
        ),
    ]
