# Generated by Django 6.0.6 on 2026-06-05 16:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0001_initial'),
        ('projects', '0004_alter_historicalproject_cover_image_and_more'),
        ('specialists', '0002_alter_historicalspecialistprofile_avatar_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='projectmembership',
            name='unique_project_specialist_role',
        ),
        migrations.AddConstraint(
            model_name='projectmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['active', 'paused'])), fields=('project', 'specialist', 'role'), name='unique_active_project_specialist_role'),
        ),
    ]
