# Generated by Django 6.0.6 on 2026-06-09 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_projectmembership_unique_project_specialist_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprojectmembership',
            name='vacancy',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Конкретная роль проекта, через которую специалист попал в команду.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.projectvacancy', verbose_name='открытая роль проекта'),
        ),
        migrations.AddField(
            model_name='projectmembership',
            name='vacancy',
            field=models.ForeignKey(blank=True, help_text='Конкретная роль проекта, через которую специалист попал в команду.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='projects.projectvacancy', verbose_name='открытая роль проекта'),
        ),
    ]
