# Generated by Django 6.0.6 on 2026-06-10 00:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0001_initial'),
        ('projects', '0006_historicalprojectmembership_vacancy_and_more'),
        ('specialists', '0003_alter_historicalspecialistprofile_timezone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='projectmembership',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('left_at__isnull', False), ('status', 'left')), models.Q(models.Q(('status', 'left'), _negated=True), ('left_at__isnull', True)), _connector='OR'), name='membership_left_at_matches_status'),
        ),
    ]
