# Generated by Django 6.0.5 on 2026-05-08 15:45

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: Frontend-разработчик, Backend-разработчик, QA-инженер.', max_length=100, unique=True, verbose_name='название роли')),
                ('slug', models.SlugField(help_text='Короткое уникальное имя для URL и фильтрации.', max_length=120, unique=True, verbose_name='URL-идентификатор')),
                ('description', models.TextField(blank=True, help_text='Краткое описание обязанностей и смысла роли.', verbose_name='описание')),
                ('is_active', models.BooleanField(default=True, help_text='Если выключено, роль не используется в новых записях.', verbose_name='активна')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
            ],
            options={
                'verbose_name': 'роль',
                'verbose_name_plural': 'роли',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: Python, Django, React, PostgreSQL.', max_length=100, unique=True, verbose_name='название технологии')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='URL-идентификатор')),
                ('category', models.CharField(choices=[('language', 'Язык программирования'), ('framework', 'Фреймворк'), ('database', 'База данных'), ('devops', 'DevOps'), ('design', 'Дизайн'), ('testing', 'Тестирование'), ('other', 'Другое')], default='other', max_length=30, verbose_name='категория')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
            ],
            options={
                'verbose_name': 'технология',
                'verbose_name_plural': 'технологии',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalRole',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Например: Frontend-разработчик, Backend-разработчик, QA-инженер.', max_length=100, verbose_name='название роли')),
                ('slug', models.SlugField(help_text='Короткое уникальное имя для URL и фильтрации.', max_length=120, verbose_name='URL-идентификатор')),
                ('description', models.TextField(blank=True, help_text='Краткое описание обязанностей и смысла роли.', verbose_name='описание')),
                ('is_active', models.BooleanField(default=True, help_text='Если выключено, роль не используется в новых записях.', verbose_name='активна')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='дата изменения')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'история изменений',
                'verbose_name_plural': 'historical роли',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTechnology',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Например: Python, Django, React, PostgreSQL.', max_length=100, verbose_name='название технологии')),
                ('slug', models.SlugField(max_length=120, verbose_name='URL-идентификатор')),
                ('category', models.CharField(choices=[('language', 'Язык программирования'), ('framework', 'Фреймворк'), ('database', 'База данных'), ('devops', 'DevOps'), ('design', 'Дизайн'), ('testing', 'Тестирование'), ('other', 'Другое')], default='other', max_length=30, verbose_name='категория')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='дата изменения')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'история изменений',
                'verbose_name_plural': 'historical технологии',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
