# Generated by Django 6.0.5 on 2026-05-08 16:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('specialists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalReview',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='Оценка от 1 до 5.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='оценка')),
                ('text', models.TextField(verbose_name='текст отзыва')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован'), ('hidden', 'Скрыт'), ('rejected', 'Отклонён')], default='draft', max_length=20, verbose_name='статус')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='дата изменения')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('author', models.ForeignKey(blank=True, db_constraint=False, help_text='Пользователь, который оставил отзыв.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='автор отзыва')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, db_constraint=False, help_text='Проект, в рамках которого оставлен отзыв.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.project', verbose_name='проект')),
                ('specialist', models.ForeignKey(blank=True, db_constraint=False, help_text='Специалист, о котором оставлен отзыв.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='specialists.specialistprofile', verbose_name='специалист')),
            ],
            options={
                'verbose_name': 'история изменений',
                'verbose_name_plural': 'historical отзывы',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='Оценка от 1 до 5.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='оценка')),
                ('text', models.TextField(verbose_name='текст отзыва')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован'), ('hidden', 'Скрыт'), ('rejected', 'Отклонён')], default='draft', max_length=20, verbose_name='статус')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('author', models.ForeignKey(help_text='Пользователь, который оставил отзыв.', on_delete=django.db.models.deletion.CASCADE, related_name='written_reviews', to=settings.AUTH_USER_MODEL, verbose_name='автор отзыва')),
                ('project', models.ForeignKey(help_text='Проект, в рамках которого оставлен отзыв.', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='projects.project', verbose_name='проект')),
                ('specialist', models.ForeignKey(help_text='Специалист, о котором оставлен отзыв.', on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to='specialists.specialistprofile', verbose_name='специалист')),
            ],
            options={
                'verbose_name': 'отзыв',
                'verbose_name_plural': 'отзывы',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('project', 'author', 'specialist'), name='unique_review_for_project_author_specialist'), models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='review_rating_between_1_and_5')],
            },
        ),
    ]
